version: "3.3"

services:
    php:
        build:
            context: ./containers/php7
            args:
               DOCKER_USER: ${DOCKER_USER}
        ports:
            - ${PHP_PORT}:9000
        volumes:
            - ${SOURCE_VOLUME}:/www
            - ./containers/php7/php-ini-overrides-${ENVIRONMENT}.ini:/usr/local/etc/php/conf.d/99-overrides.ini
        tty: true

    nginx:
        image: nginx:alpine
        container_name: nginx
        volumes:
            - ${SOURCE_VOLUME}:/www
            - ./containers/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./log/nginx:/var/log/nginx
        ports:
            - ${NGINX_PORT}:80
        links:
            - php
        tty: true
